# Generated by Django 2.2.1 on 2020-01-05 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_usingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usingplan',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usingplan',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usingplan',
            name='service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Service'),
        ),
    ]
